{{- if .Values.hooks.pre_install.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "application.labels" . | nindent 4 }}
    spec:
      restartPolicy: OnFailure
      {{- if .Values.secretMounts }}
      volumes: 
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ .Values.hooks.pre_install.name }}
        {{- if .Values.hooks.pre_install.image }}
        image: {{ .Values.hooks.pre_install.image }}
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        command: {{ .Values.hooks.pre_install.command }}
        {{- if .Values.secretMounts }}
        volumeMounts: 
          {{- range .Values.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
        {{- end }}
{{- end }}
